/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p46-gc0d1a76d
 *
 * Project: 'Blank.Debug+XMC1100-Q024x0064' 
 * Target:  'Debug+XMC1100-Q024x0064' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "XMC1100.h"



#endif /* RTE_COMPONENTS_H */
